### ISSUE TITLE
Incorrect hover shown on case class definitions

### ISSUE THREAD

**Issue by ckipp01** [sourcegraph/scip-java#495] opened 2022-08-22 07:11 UTC
I'm not sure if this is the same root issues as #482 but I've been noticing that in some files where it's just a case class defined in Scala that the hover in sourcegraph just show `def productElementName(x$1: Int): String` instead of the desired case class. You can see this here:

https://sourcegraph.com/github.com/ckipp01/mill-github-dependency-graph/-/blob/domain/src/io/kipp/github/dependency/graph/domain/Detector.scala?L10:18&popover=pinned

<img width="765" alt="Screenshot 2022-08-22 at 09 04 17" src="https://user-images.githubusercontent.com/13974112/185859404-a852e011-ce31-41cd-8f9e-6a1e73624637.png">

There are also times that the `copy` method is displayed instead of the actual case case definition like you see here:

https://sourcegraph.com/github.com/ckipp01/mill-github-dependency-graph/-/blob/domain/src/io/kipp/github/dependency/graph/domain/DependencySnapshot.scala?L16:18&popover=pinned

And finally at times I've seen it displayed as `object` as well like you can see here:

https://sourcegraph.com/github.com/ckipp01/mill-github-dependency-graph/-/blob/domain/src/io/kipp/github/dependency/graph/domain/Job.scala?L18:18&popover=pinned

I assume these are all the same root issues as #482 because these symbols are all defined in that file, albeit synthetics. And sometimes going back on the same symbol will show you a random one of the three above.

**Comment by olafurpg** [comment] 2022-08-24 12:57
Closing as duplicate of https://github.com/sourcegraph/scip-java/issues/482

The workaround is to emit LSIF directly with `scip-java index --output=dump.lsif` instead of going through the SCIP->LSIF conversion. The underlying issue is https://github.com/sourcegraph/scip/issues/52, which is to update the SCIP->LSIF conversion to handle more the scenario where multiple symbols are defined in the same location (example: Scala case classes)

**Closed by olafurpg** 2022-08-24 12:57 UTC
Labels: team/language-tools
