### ISSUE TITLE
Scala Implicit Conversion eg from Int to Long Causes the Int token to lack Precise Code Intelligence

### ISSUE THREAD

**Issue by wchau** [sourcegraph/scip-java#412] opened 2022-03-04 06:39 UTC
`lsif-java` version: `0.7.7`

Type of code: Implicit Conversion from Int to Long

Expected behavior: When an Int var / val is used as a Long parameter or converted to Long, Precise Code Intelligence should still work on the Int var / val.

Actual behavior: Definition Code Intelligence is missing. When "Find References" is clicked, ALL implicit Int to Long conversions show up in Precise Code Intelligence.

```
val a: Int = 5
val b: Long = a
```
`a` is lacking correct Precise Code Intelligence

```
def a(b: Long): Unit = {
...
}
...
val b: Int = 5
a(b)
```
`b` is lacking correct Precise Code Intelligence

I haven't tried it, but presumably, Float and Double may have the same issue (and maybe other implicit conversions I am unaware of)

**Comment by olafurpg** [comment] 2022-07-25 14:18
Thank you for reporting! This is in fact a duplicate of this issue here https://github.com/scalameta/scalameta/issues/1431 from 2018 😄 

Pending upstream fix in semanticdb-scalac https://github.com/scalameta/scalameta/pull/2797 I'll close this issue once there's a new version of semanticdb-scalac available.

**Closed** 2022-08-16 15:40 UTC
Labels: team/language-tools
